In [1]:
import pandas as pd

In [2]:
meta1 = pd.read_csv('rating_plus_hospital.csv')
meta1

id               name                          location   phonenumber  \
0        1            해오름요양병원         경기도 안산시 단원구 선부동 1034번지 8호           NaN   
1        2             세명요양병원  경기도 안산시 상록구 본오1동 904번지 13호 외 1필지           NaN   
2        3           양주큰길요양병원           경기도 양주시 광적면 가납리 495-2번지           NaN   
3        4            중앙효요양병원            경기도 의정부시 의정부동 237번지 7호           NaN   
4        5             돌담요양병원           경기도 양주시 백석읍 기산리 381-5번지           NaN   
...    ...                ...                               ...           ...   
1358  1359  의료법인홍익의료재단파스카요양병원     충청북도 청주시 청원구 내수읍 마산길 8-11, ()  043-900-1004   
1359  1360           이가양정요양병원          광주광역시 광산구 하남울로 10, (하남동)  062-675-7777   
1360  1361             평심요양병원         경상남도 양산시 하북면 신평로 37, 2~6층  055-800-7090   
1361  1362             현송요양병원        전라남도 여수시 해산4길 37-0,  (해산동)  061-691-1000   
1362  1363             혜민요양병원              강원도 평창군 봉평면 북길동길 17,  033-336-0216   

                                               category province        xpos  \
0     침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...       경기  126.807603   
1     침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...       경기  126.862995   
2     내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과       경기  126.995532   
3                                               외과, 침구과       경기  127.045456   
4                침구과, 한방내과, 가정의학과, 마취통증의학과, 외과, 신경과, 내과       경기  126.937848   
...                                                 ...      ...         ...   
1358                                              가정의학과       충북  127.538810   
1359                                              가정의학과       광주  126.802241   
1360                                              가정의학과       경남  129.086478   
1361                                              가정의학과       전남  127.633647   
1362                                              가정의학과       강원  128.376613   

           ypos  average_rating  
0     37.342222             3.2  
1     37.290667             2.2  
2     37.810187             3.0  
3     37.746234             3.5  
4     37.772088             3.1  
...         ...             ...  
1358  36.717401             1.8  
1359  35.181146             3.3  
1360  35.491624             2.3  
1361  34.802020             5.0  
1362  37.623099             4.0  

[1363 rows x 9 columns]

## 진료 카테고리 병원 추천

### 카테고리 전처리

In [3]:
category = meta1['category']
print(type(category))

<class 'pandas.core.series.Series'>


In [4]:
category.value_counts()

내과                                                                                                      1092
외과                                                                                                        66
신경과                                                                                                       28
가정의학과                                                                                                     20
신경외과                                                                                                      14
                                                                                                        ... 
한방재활의학과, 한방내과, 가정의학과, 외과, 신경과, 내과                                                                          1
내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과, 한방부인과, 침구과                                              1
내과, 신경과, 외과, 정형외과, 신경외과, 흉부외과, 피부과, 재활의학과, 가정의학과, 응급의학과, 한방내과, 한방부인과, 한방소아과, 한방안·이비인후·피부과, 한방신경정신과,        1
내과, 신경과, 외과, 산부인과  

### 요양병원 진료과목 top10  
내과              23635  
피부과             16909  
한방내과            16549  
소아청소년과          15630  
침구과             14900  
한방부인과           14535  
한방소아과           14274  
한방안·이비인후·피부과    13994  
한방신경정신과         13484  
한방재활의학과         12792  

In [5]:
top10 = ['내과','피부과','한방내과','소아청소년과','침구과','한방부인과','한방소아과','한방안·이비인후·피부과','한방신경정신과','한방재활의학과']

In [6]:
category

0       침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...
1       침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...
2       내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과
3                                                 외과, 침구과
4                  침구과, 한방내과, 가정의학과, 마취통증의학과, 외과, 신경과, 내과
                              ...                        
1358                                                가정의학과
1359                                                가정의학과
1360                                                가정의학과
1361                                                가정의학과
1362                                                가정의학과
Name: category, Length: 1363, dtype: object

### category별 리스트화

In [7]:
meta1.category.head(5)

0    침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...
1    침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...
2    내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과
3                                              외과, 침구과
4               침구과, 한방내과, 가정의학과, 마취통증의학과, 외과, 신경과, 내과
Name: category, dtype: object

### CountVectorizer : 장르를 토큰으로 만들어 벡터 생성

pip install sklearn

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
counter_vector = CountVectorizer(ngram_range=(1,5))
c_vector_category = counter_vector.fit_transform(meta1['category'])

In [9]:
c_vector_category.shape

(1363, 1275)

In [10]:
#코사인 유사도 측정
from sklearn.metrics.pairwise import cosine_similarity

similarity_category = cosine_similarity(c_vector_category, c_vector_category).argsort()[:,::-1]
print(similarity_category)

[[   0    1   55 ... 1329 1328 1362]
 [   1   55   84 ... 1270 1271 1362]
 [   2   33   58 ... 1318 1319 1335]
 ...
 [1362 1351 1343 ...  900  901    0]
 [1362 1351 1343 ...  900  901    0]
 [1362 1351 1343 ...  900  901    0]]


In [11]:
#카테고리 기반 유사도 기준으로 병원 추천
#병원 이름 적으면, 유사한 카테고리의 병원 추천
def find_sim_hospital_category(df, hospital_name, top_n=10):
    #특정 병원 카테고리 뽑기
    target_hopital_index = meta1[meta1['name'] == hospital_name].index.values
    
    #타겟 병원과 비슷한 코사인 유사도 값
    sim_index = similarity_category[target_hopital_index, :top_n].reshape(-1)
    #본인 제외
    sim_index = sim_index[sim_index!=target_hopital_index]
    
    #추천결과 새로운 df 생성. 평균평점(score)로 정렬
    result = df.iloc[sim_index].sort_values('average_rating',ascending=False)[:top_n]

    return result

In [12]:
find_sim_hospital_category(meta1, hospital_name='돌담요양병원')

id                   name                  location phonenumber  \
13  14              동두천제일요양병원      경기도 동두천시 광암동 481-3번지         NaN   
26  27                로하스요양병원      경기도 동두천시 송내동 673-4번지         NaN   
16  17                 로젠요양병원     경기도 동두천시 생연동 307-13번지         NaN   
25  26  연제의료생활협동조합가평명인암노인전문병원    경기도 가평군 상면 봉수리 49번지 4호         NaN   
44  45              메디힐포천요양병원   경기도 포천시 신북면 기지리 961-1번지         NaN   
47  48               송추효자요양병원       경기도 양주시 백석읍기산리368-3         NaN   
34  35       의료법인양지의료재단양지요양병원   경기도 이천시 호법면 매곡리 990-1번지         NaN   
40  41               포천새맘요양병원   경기도 포천시 내촌면 소학리 314-8번지         NaN   
53  54                 송추요양병원  경기도 양주시 백석읍 기산리 317번지 5호         NaN   

                                             category province        xpos  \
13        한방내과, 가정의학과, 재활의학과, 산부인과, 신경외과, 외과, 신경과, 내과       경기  127.082633   
26  침구과, 한방내과, 가정의학과, 재활의학과, 이비인후과, 신경외과, 정형외과, 외과...       경기  127.053393   
16  침구과, 한방내과, 가정의학과, 재활의학과, 비뇨의학과, 피부과, 소아청소년과, 신...       경기  127.062761   
25                      한방내과, 가정의학과, 마취통증의학과, 신경과, 내과       경기  127.304209   
44               가정의학과, 재활의학과, 피부과, 정형외과, 외과, 신경과, 내과       경기  127.226191   
47                                        외과, 신경과, 내과       경기  126.937765   
34                  한방재활의학과, 한방내과, 가정의학과, 외과, 신경과, 내과       경기  127.377768   
40             침구과, 한방재활의학과, 한방내과, 가정의학과, 외과, 신경과, 내과       경기  127.248744   
53                               침구과, 한방내과, 가정의학과, 내과       경기  126.940708   

         ypos  average_rating  
13  37.894908             5.0  
26  37.881560             4.0  
16  37.899207             4.0  
25  37.840848             3.4  
44  37.934860             3.2  
47  37.771043             3.0  
34  37.187584             3.0  
40  37.794550             2.5  
53  37.776780             1.6

In [ ]:
돌담병원 = 침구과, 한방내과, 가정의학과, 마취통증의학과, 외과, 신경과, 내과

### TF-IDF 벡터화  
단어를 갯수 그대로 카운트하지 않고 모든 문서에 공통적으로 들어있는 단어의 경우 문서 구별 능력이 떨어진다고 보아 가중치를 축소하는 방법

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vector = TfidfVectorizer()
#tfidf_vector = TfidfVectorizer(ngram_range=(1,2))

tfidf_matrix = tfidf_vector.fit_transform(meta1['category']).toarray()
#tfidf_matrix = tfidf_vector.fit_transform(movie_data['genres'] + " " + movie_data['keywords']).toarray()
tfidf_matrix_feature = tfidf_vector.get_feature_names()

C:\Users\leeej\miniconda3\envs\practice\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [54]:
tfidf_matrix.shape

(1348, 35)